import { Video, Comment } from "./types";

export const VIDEOS: Video[] = [
  // --- PAGE 1: VIDEOS 1 to 12 ---
  {
    id: "v1",
    title: "Exploring the Future of Quantum Computing",
    description: "In this episode, we dive deep into the world of quantum mechanics and how qubits are changing the future of modern computation. Learn about supercomputers, error correction, and real-world quantum applications.",
    thumbnailUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    channelName: "TechHorizon",
    channelAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.4M",
    views: "245K",
    publishedAt: "2 days ago",
    duration: "12:14",
    category: "Tech & Science",
    likes: "18K",
    dislikes: "124"
  },
  {
    id: "v2",
    title: "10 Hidden Islands in the Mediterranean You Must Visit",
    description: "Travel with us to the most secluded and untouched islands in Greece, Italy, and Croatia. Clean turquoise waters, historic coastal villages, and authentic local food away from the main tourist hubs.",
    thumbnailUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    channelName: "Wanderlust Chronicles",
    channelAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    subscribers: "850K",
    views: "412K",
    publishedAt: "1 week ago",
    duration: "8:42",
    category: "Travel",
    likes: "32K",
    dislikes: "430"
  },
  {
    id: "v3",
    title: "Deep Focus Ambient Beats for Coding & Studying",
    description: "A seamless mix of low-fidelity synthesizers, relaxing nature soundscapes, and steady drum kicks designed to maximize your concentration, study sessions, or coding marathons.",
    thumbnailUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    channelName: "The Sound Sanctuary",
    channelAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    subscribers: "3.2M",
    views: "1.8M",
    publishedAt: "3 weeks ago",
    duration: "9:56",
    category: "Music",
    likes: "95K",
    dislikes: "180"
  },
  {
    id: "v4",
    title: "Cinematic Journey Through the Nordic Wilderness",
    description: "Stunning 4K aerial footage showcasing the deep fjords, volcanic black-sand beaches, and ancient moss-grown forests of Norway and Iceland. Experience nature in its rawest, most magnificent state.",
    thumbnailUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    channelName: "Terra Cinema",
    channelAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.2M",
    views: "520K",
    publishedAt: "5 days ago",
    duration: "10:53",
    category: "Nature",
    likes: "45K",
    dislikes: "210"
  },
  {
    id: "v5",
    title: "Building a Modern Minimalist Desk Setup from Scratch",
    description: "Watch the full walkthrough of designing, routing cables, and assembling a customized height-adjustable wooden desk setup. Includes smart lights, workspace ergonomics, and premium peripheral choices.",
    thumbnailUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    channelName: "Workspace Design",
    channelAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    subscribers: "410K",
    views: "189K",
    publishedAt: "4 days ago",
    duration: "11:47",
    category: "Design",
    likes: "12K",
    dislikes: "95"
  },
  {
    id: "v6",
    title: "Mastering Next-Gen Unreal Engine 5 Real-time Lights",
    description: "Learn how to use Lumen and Nanite in Unreal Engine 5 to create hyper-realistic environments with real-time global illumination, soft shadows, and high-performance landscape geometry.",
    thumbnailUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    channelName: "Pixel Academy",
    channelAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    subscribers: "670K",
    views: "98K",
    publishedAt: "6 days ago",
    duration: "15:00",
    category: "Gaming & Dev",
    likes: "7.8K",
    dislikes: "42"
  },
  {
    id: "v7",
    title: "Street Food Tour: Inside Tokyo's Hidden Alleyways",
    description: "We navigate the busy side streets of Shinjuku and Omoide Yokocho to taste traditional yakitori, sizzling takoyaki, custom craft ramen, and unique matcha-infused desserts from generational masters.",
    thumbnailUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    channelName: "Taste Seekers",
    channelAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    subscribers: "2.1M",
    views: "890K",
    publishedAt: "3 days ago",
    duration: "14:15",
    category: "Food",
    likes: "61K",
    dislikes: "320"
  },
  {
    id: "v8",
    title: "How Space Telescopes Capture Cosmic History",
    description: "Unravel the mechanics of infrared imaging and gravitational lensing. We explain how modern space observatories peer billions of light-years back in time to capture the birth of the earliest galaxies.",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    channelName: "Cosmos Explained",
    channelAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.8M",
    views: "340K",
    publishedAt: "10 hours ago",
    duration: "13:15",
    category: "Tech & Science",
    likes: "29K",
    dislikes: "94"
  },
  {
    id: "v9",
    title: "Custom Mechanical Keyboard Build & Sound Test",
    description: "Lubing linear switches, adding premium brass plates, and putting together a custom 75% aluminum keyboard. Absolute typing ASMR sounds included at the end of the video.",
    thumbnailUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    channelName: "Keeb Lab",
    channelAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80",
    subscribers: "320K",
    views: "72K",
    publishedAt: "12 days ago",
    duration: "10:30",
    category: "Design",
    likes: "4.5K",
    dislikes: "18"
  },
  {
    id: "v10",
    title: "Behind the Scenes: Directing a Low-Budget Sci-Fi Film",
    description: "An authentic breakdown of practical lighting, smart green-screen keying, and visual effects composting to achieve a Hollywood-grade retro science fiction aesthetic on an indie budget.",
    thumbnailUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    channelName: "Indie Filmmaker",
    channelAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80",
    subscribers: "540K",
    views: "112K",
    publishedAt: "2 weeks ago",
    duration: "12:14",
    category: "Gaming & Dev",
    likes: "8.9K",
    dislikes: "72"
  },
  {
    id: "v11",
    title: "15 Essential Survival Skills for Extreme Environments",
    description: "Our wilderness coach explains building windproof temporary shelters, purifying muddy water using simple tools, starting fire in damp conditions, and signaling for emergency extraction.",
    thumbnailUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    channelName: "Survive & Adapt",
    channelAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    subscribers: "920K",
    views: "305K",
    publishedAt: "5 days ago",
    duration: "8:48",
    category: "Nature",
    likes: "19K",
    dislikes: "156"
  },
  {
    id: "v12",
    title: "The Physics of High-Performance Sports Cars",
    description: "We analyze downforce, drag coefficients, active suspension systems, and torque vectoring mechanics that enable modern hypercars to corner at mind-bending G-forces.",
    thumbnailUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    channelName: "Apex Engineering",
    channelAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.1M",
    views: "215K",
    publishedAt: "1 day ago",
    duration: "15:15",
    category: "Tech & Science",
    likes: "14K",
    dislikes: "89"
  },

  // --- PAGE 2: VIDEOS 13 to 24 ---
  {
    id: "v13",
    title: "Ultimate Solo Trek Across the Alpine Ridge",
    description: "A breathtaking self-shot journey walking the ridge lines of Switzerland, traversing high passes, and camping above the cloud line. Total gear breakdown and route details included.",
    thumbnailUrl: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    channelName: "Wanderlust Chronicles",
    channelAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    subscribers: "850K",
    views: "642K",
    publishedAt: "3 weeks ago",
    duration: "9:56",
    category: "Travel",
    likes: "49K",
    dislikes: "110"
  },
  {
    id: "v14",
    title: "The Architecture of Soundproof Recording Studios",
    description: "How decoupled room-within-a-room layouts, dense rockwool insulation, custom acoustic diffusers, and bass traps are constructed to create absolutely perfect audio tracking environments.",
    thumbnailUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    channelName: "Workspace Design",
    channelAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    subscribers: "410K",
    views: "93K",
    publishedAt: "9 days ago",
    duration: "10:53",
    category: "Design",
    likes: "6.2K",
    dislikes: "34"
  },
  {
    id: "v15",
    title: "Deep Sea Exploration: 4,000 Meters Below the Surface",
    description: "Descend into the Midnight Zone to witness hyper-rare bioluminescent organisms, active hydrothermal vents, and the alien ecosystems that thrive in complete darkness under crushing pressure.",
    thumbnailUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    channelName: "Terra Cinema",
    channelAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.2M",
    views: "720K",
    publishedAt: "1 month ago",
    duration: "8:48",
    category: "Nature",
    likes: "58K",
    dislikes: "240"
  },
  {
    id: "v16",
    title: "A Complete Guide to CSS Grid & Modern Web Layouts",
    description: "Forget floats and absolute position. Learn CSS Grid structures, grid areas, dense packing layouts, and dynamic auto-fit behaviors to build robust responsive dashboards in under 15 minutes.",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    channelName: "TechHorizon",
    channelAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.4M",
    views: "156K",
    publishedAt: "6 days ago",
    duration: "11:47",
    category: "Tech & Science",
    likes: "10K",
    dislikes: "52"
  },
  {
    id: "v17",
    title: "Lo-Fi Guitar Session: Midnight Jazz Melodies",
    description: "A calming live-recorded session featuring vintage semi-hollow body jazz guitar riffs blended with soft rain drops. Perfect background audio for programming, reading, or sleep.",
    thumbnailUrl: "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    channelName: "The Sound Sanctuary",
    channelAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    subscribers: "3.2M",
    views: "950K",
    publishedAt: "2 weeks ago",
    duration: "12:14",
    category: "Music",
    likes: "74K",
    dislikes: "140"
  },
  {
    id: "v18",
    title: "How to Cook the Perfect Ribeye Steak at Home",
    description: "A professional chef demonstrates reverse searing, butter basting with fresh rosemary and garlic cloves, internal temperature monitoring, and the crucial resting phase for juicy results.",
    thumbnailUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    channelName: "Taste Seekers",
    channelAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    subscribers: "2.1M",
    views: "1.2M",
    publishedAt: "3 days ago",
    duration: "15:00",
    category: "Food",
    likes: "89K",
    dislikes: "610"
  },
  {
    id: "v19",
    title: "Why Mars Is Harder to Colonize Than You Think",
    description: "We investigate atmospheric radiation, perchlorate soil toxicity, the psychological challenges of extreme isolation, and the engineering limitations of rocket fuel production on the Red Planet.",
    thumbnailUrl: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    channelName: "Cosmos Explained",
    channelAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.8M",
    views: "530K",
    publishedAt: "12 days ago",
    duration: "14:15",
    category: "Tech & Science",
    likes: "38K",
    dislikes: "190"
  },
  {
    id: "v20",
    title: "Pro Esports Tips: How to Master Precision Aiming",
    description: "A complete analysis of mouse sensitivity, muscle memory exercises, crosshair positioning discipline, and reaction speed routines used by world-champion tactical shooter players.",
    thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    channelName: "Pixel Academy",
    channelAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    subscribers: "670K",
    views: "185K",
    publishedAt: "8 days ago",
    duration: "13:15",
    category: "Gaming & Dev",
    likes: "15K",
    dislikes: "105"
  },
  {
    id: "v21",
    title: "10 Essential Hand Tools Every Maker Needs",
    description: "We highlight the most reliable, durable hand tools for woodcarving, metalcraft, and rapid prototyping. Learn proper maintenance, sharpening techniques, and organizing systems.",
    thumbnailUrl: "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    channelName: "Keeb Lab",
    channelAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80",
    subscribers: "320K",
    views: "64K",
    publishedAt: "2 weeks ago",
    duration: "10:30",
    category: "Design",
    likes: "3.8K",
    dislikes: "15"
  },
  {
    id: "v22",
    title: "Secrets of Lighting for Cinematic Portraits",
    description: "Learn key lighting, fill ratios, bounce boards, and rim light techniques. We replicate classic cinema close-ups in a standard living room setting using cheap LED panels.",
    thumbnailUrl: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    channelName: "Indie Filmmaker",
    channelAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80",
    subscribers: "540K",
    views: "148K",
    publishedAt: "1 month ago",
    duration: "12:14",
    category: "Gaming & Dev",
    likes: "11K",
    dislikes: "92"
  },
  {
    id: "v23",
    title: "Exploring the Ancient Redwood Canopy",
    description: "Climbing into the upper tiers of California's ancient redwoods to research tree ecosystems. Pristine nature footage, local wildlife encounters, and dynamic forest audio.",
    thumbnailUrl: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    channelName: "Survive & Adapt",
    channelAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    subscribers: "920K",
    views: "210K",
    publishedAt: "10 days ago",
    duration: "8:48",
    category: "Nature",
    likes: "15K",
    dislikes: "120"
  },
  {
    id: "v24",
    title: "How Fighter Jets Achieve Supersonic Flight",
    description: "An in-depth explanation of afterburners, variable geometry air intakes, delta wings, and how pilots manage extreme pressure changes when breaking the sound barrier.",
    thumbnailUrl: "https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    channelName: "Apex Engineering",
    channelAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.1M",
    views: "390K",
    publishedAt: "5 days ago",
    duration: "15:15",
    category: "Tech & Science",
    likes: "25K",
    dislikes: "110"
  },

  // --- PAGE 3: VIDEOS 25 to 36 ---
  {
    id: "v25",
    title: "Living in a Remote Cabin in the Canadian Woods",
    description: "A day-in-the-life walkthrough of living completely off the power grid. Splitting seasoned firewood, cooking on a cast-iron stove, fetching well water, and enjoying the serene forest silence.",
    thumbnailUrl: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    channelName: "Terra Cinema",
    channelAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.2M",
    views: "980K",
    publishedAt: "2 weeks ago",
    duration: "8:48",
    category: "Nature",
    likes: "78K",
    dislikes: "320"
  },
  {
    id: "v26",
    title: "Unboxing the Ultimate Futuristic VR Headset",
    description: "We review the highest-resolution standalone VR headset on the market. Testing hand-tracking fidelity, passthrough mixed reality clarity, and high-intensity gaming experiences.",
    thumbnailUrl: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    channelName: "TechHorizon",
    channelAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.4M",
    views: "310K",
    publishedAt: "4 days ago",
    duration: "12:14",
    category: "Tech & Science",
    likes: "22K",
    dislikes: "145"
  },
  {
    id: "v27",
    title: "10-Hour Deep Healing Tibetan Singing Bowls",
    description: "Beautifully tuned pure resonance frequencies and Tibetan bowls recorded with studio microphones. Perfect for deep sleep, transcendental meditation, or stress-relief cycles.",
    thumbnailUrl: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    channelName: "The Sound Sanctuary",
    channelAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    subscribers: "3.2M",
    views: "2.4M",
    publishedAt: "1 month ago",
    duration: "9:56",
    category: "Music",
    likes: "115K",
    dislikes: "310"
  },
  {
    id: "v28",
    title: "Exploring the Ancient Temples of Kyoto at Night",
    description: "Walk under the glowing lanterns and bamboo groves in late autumn. This cinematic journey captures Kyoto's historical preservation and deep spiritual atmospheres after dark.",
    thumbnailUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    channelName: "Wanderlust Chronicles",
    channelAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    subscribers: "850K",
    views: "530K",
    publishedAt: "2 weeks ago",
    duration: "10:53",
    category: "Travel",
    likes: "41K",
    dislikes: "210"
  },
  {
    id: "v29",
    title: "Making Handmade Ceramic Tea Bowls (Full Process)",
    description: "The complete wheel-throwing, dynamic trimming, glaze formulation, and high-heat kiln wood firing processes to create pristine, rustic Japanese-style tea ceramics.",
    thumbnailUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    channelName: "Keeb Lab",
    channelAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80",
    subscribers: "320K",
    views: "89K",
    publishedAt: "8 days ago",
    duration: "11:47",
    category: "Design",
    likes: "5.4K",
    dislikes: "22"
  },
  {
    id: "v30",
    title: "The Ultimate Homemade Neapolitan Pizza Recipe",
    description: "Learn how to achieve a perfectly charred, puffy cornicione crust in a standard domestic oven using baking steels, simple flour hydration techniques, and fresh San Marzano tomatoes.",
    thumbnailUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    channelName: "Taste Seekers",
    channelAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    subscribers: "2.1M",
    views: "1.5M",
    publishedAt: "1 week ago",
    duration: "15:00",
    category: "Food",
    likes: "105K",
    dislikes: "540"
  },
  {
    id: "v31",
    title: "Deep Dive: How Compilers Transform Code into Bits",
    description: "A visual explanation of lexical analysis, abstract syntax trees (AST), intermediate representation optimization, and assembly generation. Essential knowledge for core software engineers.",
    thumbnailUrl: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    channelName: "Pixel Academy",
    channelAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
    subscribers: "670K",
    views: "240K",
    publishedAt: "3 weeks ago",
    duration: "14:15",
    category: "Gaming & Dev",
    likes: "19K",
    dislikes: "110"
  },
  {
    id: "v32",
    title: "Journey to the Center of a Supermassive Black Hole",
    description: "What happens when you cross the event horizon? We visual-model general relativity equations, time dilation effects, and spaghettification using high-performance physics rendering pipelines.",
    thumbnailUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    channelName: "Cosmos Explained",
    channelAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.8M",
    views: "1.1M",
    publishedAt: "10 days ago",
    duration: "13:15",
    category: "Tech & Science",
    likes: "82K",
    dislikes: "340"
  },
  {
    id: "v33",
    title: "15-Minute Daily Guided Mindfulness Meditation",
    description: "A calming morning meditation focusing on breath awareness, body scans, and establishing clarity, gratitude, and physical calmness to start your busy day centered.",
    thumbnailUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    channelName: "The Sound Sanctuary",
    channelAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    subscribers: "3.2M",
    views: "340K",
    publishedAt: "5 days ago",
    duration: "10:30",
    category: "Music",
    likes: "21K",
    dislikes: "55"
  },
  {
    id: "v34",
    title: "How to Soundproof Your Home Office (Budget Guide)",
    description: "Stop external noises from ruining your web calls. We test cheap acoustic blankets, door sweepers, dynamic weather-stripping seals, and smart microphone noise cancelation.",
    thumbnailUrl: "https://images.unsplash.com/photo-1493934558415-9d19f0b2b4d2?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    channelName: "Workspace Design",
    channelAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80",
    subscribers: "410K",
    views: "115K",
    publishedAt: "12 days ago",
    duration: "12:14",
    category: "Design",
    likes: "7.1K",
    dislikes: "45"
  },
  {
    id: "v35",
    title: "Fjord Kayaking: Traversing the Deep Norwegian Channels",
    description: "Kayaking along sheer rock walls towering 1,000 meters overhead. Discovering isolated waterfalls, listening to cracking sea glaciers, and paddling side-by-side with wild marine life.",
    thumbnailUrl: "https://images.unsplash.com/photo-1530866495561-507c9faab2ed?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    channelName: "Wanderlust Chronicles",
    channelAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
    subscribers: "850K",
    views: "220K",
    publishedAt: "12 hours ago",
    duration: "8:48",
    category: "Travel",
    likes: "18K",
    dislikes: "42"
  },
  {
    id: "v36",
    title: "The Mechanics of Jet Engines and Gas Turbines",
    description: "We break down core compressor blades, high-temperature combustion chambers, thrust vector nozzle structures, and how fuel burns efficiently at extreme high altitude temperatures.",
    thumbnailUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&auto=format&fit=crop&q=80",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    channelName: "Apex Engineering",
    channelAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&auto=format&fit=crop&q=80",
    subscribers: "1.1M",
    views: "480K",
    publishedAt: "2 days ago",
    duration: "15:15",
    category: "Tech & Science",
    likes: "32K",
    dislikes: "120"
  }
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  v1: [
    {
      id: "c1",
      authorName: "Sarah Connor",
      authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
      text: "This explanation of qubits and coherence states is the clearest I have ever watched! Incredible animations and pacing.",
      likes: 1240,
      publishedAt: "1 day ago"
    },
    {
      id: "c2",
      authorName: "David M.",
      authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
      text: "As a quantum engineering student, I appreciate how you addressed the noise and error correction hurdles. Truly brilliant content.",
      likes: 412,
      publishedAt: "18 hours ago"
    },
    {
      id: "c3",
      authorName: "Alice Woods",
      authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
      text: "Excellent production. Subscribed immediately. Looking forward to the next episode about superconducting qubits!",
      likes: 89,
      publishedAt: "12 hours ago"
    }
  ],
  v2: [
    {
      id: "c1",
      authorName: "Marco Rossi",
      authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
      text: "Adding these islands to my summer itinerary! That third Greek island is a secret gem.",
      likes: 532,
      publishedAt: "4 days ago"
    },
    {
      id: "c2",
      authorName: "Emma Watson",
      authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      text: "The camera work in this video is simply breathtaking. Feels like I'm already there.",
      likes: 104,
      publishedAt: "2 days ago"
    }
  ],
  v3: [
    {
      id: "c1",
      authorName: "Logan Code",
      authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80",
      text: "This beat is literally compiling my code and fixing bugs for me. On repeat for 8 hours!",
      likes: 2450,
      publishedAt: "2 weeks ago"
    },
    {
      id: "c2",
      authorName: "Chloe S.",
      authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80",
      text: "The rain overlay matches the visual aesthetic perfectly. Super atmospheric.",
      likes: 580,
      publishedAt: "1 week ago"
    }
  ]
};

// Generate default mock comments for other videos dynamically if they don't exist
export function getCommentsForVideo(videoId: string): Comment[] {
  if (MOCK_COMMENTS[videoId]) {
    return MOCK_COMMENTS[videoId];
  }
  
  // Generic comments
  return [
    {
      id: `c_${videoId}_1`,
      authorName: "Alex Mercer",
      authorAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80",
      text: "This is super high quality content! YouTube needs more creators like this.",
      likes: 45,
      publishedAt: "3 days ago"
    },
    {
      id: `c_${videoId}_2`,
      authorName: "Sophia Martinez",
      authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
      text: "Wow, I am impressed by the edits and the pacing of this video. Subscribed!",
      likes: 21,
      publishedAt: "1 day ago"
    },
    {
      id: `c_${videoId}_3`,
      authorName: "James Peterson",
      authorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80",
      text: "Can anyone tell me what song is playing in the background at 4:15? Awesome video!",
      likes: 8,
      publishedAt: "6 hours ago"
    }
  ];
}
